### ISSUE TITLE
Converting Address Book dropdown select options to radio buttons

### ISSUE THREAD

**Issue by wahabmalik1211** [crosspeaksoftware/woo-address-book#146]
How to show radio buttons instead of dropdown list to select addresses from the saved ones

**Comment by matt-h** [comment]
We don't have a way to use radio buttons at the moment.

What you could do is look at the `checkout_address_select_field` function in the `includes/class-wc-address-book.php` file. You can unhook that function which creates the select with:

```php
remove_filter( 'woocommerce_checkout_fields', array( WC_Address_Book::get_instance(), 'checkout_address_select_field' ), 9999, 1 );
```

Then implement your own version of that function on the `woocommerce_checkout_fields` filter that creates radio buttons instead of select fields.
